//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartPractise.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryId { get; set; }
        public string Amount { get; set; }
        public bool Status { get; set; }
    }
}
